# Generated by Django 3.1 on 2020-09-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.CharField(choices=[('b', 'Bad'), ('a', 'Average'), ('e', 'Excellent')], default='a', max_length=1),
            preserve_default=False,
        ),
    ]
